### ISSUE TITLE
[Error] Promise rejection error

### ISSUE THREAD

**Issue by digi0ps** [revisiit/fantastic-froyo#3]
Look into the error for more details.
Happens while just getting.

<img width="772" alt="Screenshot 2019-06-13 at 1 48 52 AM" src="https://user-images.githubusercontent.com/3889675/59408418-a35d6900-8dd1-11e9-955f-d45180862d26.png">

Fix it when possible. 

cc: @TheMightyRaider

**Comment by digi0ps** [comment]
Not closed yet, I will fix it.

**Comment by TheMightyRaider** [comment]
Why is it showing for you alone ?

**Comment by digi0ps** [comment]
We aren't handling a catch

**Comment by TheMightyRaider** [comment]
Still not resolved ?

**Comment by digi0ps** [comment]
Haven't encountered this after that. Closing.
